stages:
  - build
  - test
  - release

variables:
  CONTAINER_TEST_IMAGE: boileaum/rosen:$CI_COMMIT_REF_NAME
  CONTAINER_RELEASE_IMAGE: boileaum/rosen:latest

#before_script:
# - echo $DOCKERHUB_PASSWD | docker login -u boileaum --password-stdin

b:docker:
  stage: build
  tags:
    - shell, docker
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE -f ./docker/Dockerfile-rosen .
    - docker push $CONTAINER_TEST_IMAGE

t:rosen:
  stage: test
  tags:
    - shell, docker
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run $CONTAINER_TEST_IMAGE /bin/bash -c 'pytest -v'

t:rosen-py36:
  stage: test
  image: boileaum/pythran:latest
  tags:
    - tp-gitlab-ci, docker
  script:
    - source /home/euler/py36/bin/activate 
    - make clean && make
    - pytest -v

t:rosen-py27:
  stage: test
  image: boileaum/pythran:latest
  tags:
    - shell, docker
  script:
    - source /home/euler/py27/bin/activate 
    - make clean && make
    - pytest -v

r:docker:
  stage: release
  tags:
    - shell, docker
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - exo3

