pages:
  tags:
    - pages, docker
  image: jupyter/minimal-notebook
  script:
    - mkdir public
    - ./make_slides.sh
    - ./make_archive.sh
  artifacts:
    paths:
      - public
  only:
    - master

