pages:
  tags:
    - docker-exec
    - tp-gitlab-ci
  image: jupyter/minimal-notebook
  script:
    - mkdir public
    - ./scripts/make_slides.sh
    - ./scripts/make_archive.sh
  artifacts:
    paths:
      - public
  only:
    - master

