stages:
  - build
  - test
  - release

variables:
  DOCKERHUB_USERNAME: boileaum
  CONTAINER_TEST_IMAGE: $DOCKERHUB_USERNAME/rosen:$CI_COMMIT_REF_NAME
  CONTAINER_RELEASE_IMAGE: $DOCKERHUB_USERNAME/rosen:latest

b:docker:
  stage: build
  tags:
    - shell
    - docker
  script:
    - echo $DOCKERHUB_PASSWD | docker login -u $DOCKERHUB_USERNAME --password-stdin
    - docker build --pull -t $CONTAINER_TEST_IMAGE -f ./docker/Dockerfile-rosen .
    - docker push $CONTAINER_TEST_IMAGE

t:rosen-py36:
  stage: test
  image: $CONTAINER_TEST_IMAGE
  tags:
    - tp-gitlab-ci
    - docker-exec
  script:
    - make clean && make
    - pytest -v

t:rosen-py27:
  stage: test
  image: $CONTAINER_TEST_IMAGE
  tags:
    - tp-gitlab-ci
    - docker-exec
  script:
    - source /home/euler/py27/bin/activate 
    - make clean && make
    - pytest -v

r:docker:
  stage: release
  tags:
    - shell
    - docker
  script:
    - echo $DOCKERHUB_PASSWD | docker login -u $DOCKERHUB_USERNAME --password-stdin
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - exo3

