FROM python:3
MAINTAINER Matthieu Boileau <matthieu.boileau@math.unistra.fr>

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

RUN apt-get update --fix-missing && \
      apt-get install -y \
      vim

RUN apt-get clean && \
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN useradd -m -s /bin/bash  euler
ENV HOME /home/euler
RUN chown -R euler:euler /home/euler
USER euler
WORKDIR $HOME

CMD /bin/bash

